<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationIcon>ui/maple_leaf.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <None Remove="ui/**/*.png;ui/**/*.svg"/>
    <Resource Include="ui/**/*.png;ui/**/*.svg" Exclude="ui/center/append_word.svg"/>
  </ItemGroup>
</Project>
